// Front-End Application Actions
export const TOGGLE_NAV_MENU = 'TOGGLE_NAV_MENU'
export const TOGGLE_USER_MENU = 'TOGGLE_USER_MENU'
export const TOGGLE_HOME_MODAL = 'TOGGLE_HOME_MODAL'
export const TOGGLE_TIMEOUT_MODAL = 'TOGGLE_TIMEOUT_MODAL'
export const SET_TITLE = 'SET_TITLE'
export const USER_NAV = "USER_NAV"
export const USER_HOME = "USER_HOME"
export const CREATE_MESSAGE = 'CREATE_MESSAGE'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'

// Auth Actions
export const REGISTER_USER = 'REGISTER_USER'
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR'
export const CLEAR_REGISTRATION_ERRORS = 'CLEAR_REGISTRATION_ERRORS'
export const TOKEN_EXPIRATION_CHECK = 'TOKEN_EXPIRATION_CHECK'
export const TOKEN_EXPIRED = 'TOKEN_EXPIRED'
export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR'
export const VERIFYING_USER = 'VERIFYING_USER'
export const USER_VERIFIED = 'USER_VERIFIED'
export const VERIFICATION_ERROR = 'VERIFICATION_ERROR'

// E-Mail Actions
export const SENDING_EMAIL = 'SENDING_EMAIL'
export const EMAIL_SUCCESS = 'EMAIL_SUCCESS'
export const EMAIL_ERROR = 'EMAIL_ERROR'

// Inventory Actions
export const GET_CATEGORIES = "GET_CATEGORIES"
export const GET_CATEGORY = "GET_CATEGORY"
export const CLEAR_CATEGORY = "CLEAR_CATEGORY"
export const GET_ITEMS = "GET_ITEMS"
export const DELETE_ITEM = "DELETE_ITEM"
export const CREATE_ITEM = "CREATE_ITEM"

// Financial Account Actions
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT'
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT'
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT'
export const ACCOUNT_LOADING = 'ACCOUNT_LOADING'
export const ACCOUNT_LOADED = 'ACCOUNT_LOADED'
export const ACCOUNT_LOAD_ERROR= 'ACCOUNT_LOAD_ERROR'
export const ACCOUNTS_LOADING = 'ACCOUNTS_LOADING'
export const ACCOUNTS_LOADED = 'ACCOUNTS_LOADED'
export const ACCOUNTS_LOAD_ERROR = 'ACCOUNTS_LOAD_ERROR'
export const ACCOUNT_DELETING = "ACCOUNT_DELETING"
export const CLEAR_ACCOUNT = 'CLEAR_ACCOUNT'

// Financial Transaction Actions
export const TRANSACTIONS_LOADING = 'TRANSACTIONS_LOADING'
export const TRANSACTIONS_LOADED = 'TRANSACTIONS_LOADED'
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION'
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION'
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION'
export const CLEAR_TRANSACTIONS = 'CLEAR_TRANSACTIONS'
export const TRANSACTIONS_LOAD_ERROR = 'TRANSACTIONS_LOAD_ERROR'
export const TRANSACTION_SELECTED = 'TRANSACTION_SELECTED'
export const CLEAR_TRANSACTION = 'CLEAR_TRANSACTION'
export const SAVING_TRANSACTION = 'SAVING_TRANSACTION'
export const TRANSACTION_SAVED = 'TRANSACTION_SAVED'
export const TRANSACTION_SAVE_ERROR = 'TRANSACTION_SAVE_ERROR'
export const TOGGLE_TRANSACTION_MODAL = 'TOGGLE_TRANSACTION_MODAL'

// Asset Actions
export const ASSETS_LOADING = 'ASSETS_LOADING'
export const ASSETS_LOADED = 'ASSETS_LOADED'
export const CREATE_ASSET = 'CREATE_ASSET'
export const UPDATE_ASSET = 'UPDATE_ASSET'
export const DELETE_ASSET = 'DELETE_ASSET'
export const GET_ASSET = 'GET_ASSET'
export const CLEAR_ASSET = 'CLEAR_ASSET'

// Financial DashboardActions
export const NET_WORTH_LOADING = 'NET_WORTH_LOADING'
export const NET_WORTH_LOADED = 'NET_WORTH_LOADED'
export const NET_WORTH_LOAD_ERROR = 'NET_WORTH_LOAD_ERROR'
export const RESET_NET_WORTH = 'RESET_NET_WORTH'

// Financial Institution Actions
export const GET_FINANCIAL_CATEGORIES = 'GET_FINANCIAL_CATEGORIES'
export const GET_FINANCIAL_INSTITUTIONS = 'GET_FINANCIAL_INSTITUTIONS'
export const GET_FINANCIAL_INSTITUTION = 'GET_FINANCIAL_INSTITUTION'

// Home Actions
export const GET_HOMES = 'GET_HOMES'
export const GET_HOME = 'GET_HOME'
export const CLEAR_HOME = 'CLEAR_HOME'
export const CREATE_HOME = 'CREATE_HOME'
export const UPDATE_HOME = 'UPDATE_HOME'
export const DELETE_HOME = 'DELETE_HOME'

// Organization Actions
export const ORGANIZATIONS_LOADING = 'ORGANIZATIONS_LOADING'
export const ORGANIZATIONS_LOADED = 'ORGANIZATIONS_LOADED'
export const ORGANIZATIONS_LOAD_ERROR = 'ORGANIZATIONS_LOAD_ERROR'
export const ORGANIZATION_LOADING = 'ORGANIZATION_LOADING'
export const ORGANIZATION_LOADED = 'ORGANIZATION_LOADED'
export const ORGANIZATION_LOAD_ERROR = 'ORGANIZATION_LOAD_ERROR'
export const CREATE_ORGANIZATION = 'CREATE_ORGANIZATION'
export const UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION'
export const ORGANIZATION_DELETING = 'ORGANIZATION_DELETING'
export const DELETE_ORGANIZATION = 'DELETE_ORGANIZATION'
export const CLEAR_ORGANIZATION = 'CLEAR_ORGANIZATION'
export const SAVE_ORGANIZATION = 'SAVE_ORGANIZATION'

